# Generated by Django 3.0.6 on 2020-05-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getter_btc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btc',
            old_name='date',
            new_name='timestamp',
        ),
    ]
